amcl:
  ros__parameters:
    use_sim_time: False
    base_frame_id: "base_link"
    global_frame_id: "map"
    odom_frame_id: "odom"
    max_particles: 2000
    min_particles: 500
    update_min_d: 0.25
    update_min_a: 0.2
    laser_model_type: "likelihood_field"
    laser_max_range: 12.0
    laser_min_range: 0.1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"  # ✅ 수정
    tf_broadcast: true
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
